# Generated by Django 4.1.1 on 2023-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
