# Generated by Django 4.1.5 on 2023-02-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='question',
        ),
    ]
