# Generated by Django 4.1.5 on 2023-03-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_options_alter_comments_text_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
